# Generated by Django 4.2.11 on 2025-12-27 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargaCombustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('kilometraje', models.PositiveIntegerField(help_text='Kilometraje al momento de la carga')),
                ('litros', models.DecimalField(decimal_places=2, help_text='Litros cargados', max_digits=6)),
                ('precio_litro', models.DecimalField(decimal_places=2, help_text='Precio por litro', max_digits=6)),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tipo_combustible', models.CharField(choices=[('EXTRA', 'Extra'), ('SUPER', 'Super'), ('ECOPAIS', 'Ecopaís'), ('DIESEL', 'Diesel')], max_length=10)),
                ('estacion_servicio', models.CharField(blank=True, max_length=100, null=True)),
                ('tanque_lleno', models.BooleanField(default=False, help_text='Indica si se llenó el tanque completamente')),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargas_combustible', to='vehicles.vehiculo')),
            ],
            options={
                'verbose_name': 'Carga de Combustible',
                'verbose_name_plural': 'Cargas de Combustible',
                'ordering': ['-fecha'],
            },
        ),
    ]
