# Generated by Django 4.2.11 on 2025-12-27 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('tipo', models.CharField(choices=[('PREVENTIVO', 'Preventivo'), ('CORRECTIVO', 'Correctivo'), ('EMERGENCIA', 'Emergencia')], max_length=15)),
                ('categoria', models.CharField(choices=[('MOTOR', 'Motor'), ('FRENOS', 'Frenos'), ('SUSPENSION', 'Suspensión'), ('ELECTRICO', 'Eléctrico'), ('TRANSMISION', 'Transmisión'), ('NEUMATICOS', 'Neumáticos'), ('CARROCERIA', 'Carrocería'), ('CLIMATIZACION', 'Climatización'), ('OTRO', 'Otro')], max_length=15)),
                ('descripcion', models.TextField()),
                ('kilometraje', models.PositiveIntegerField(help_text='Kilometraje al momento del mantenimiento')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taller', models.CharField(blank=True, max_length=100, null=True)),
                ('repuestos_utilizados', models.TextField(blank=True, help_text='Lista de repuestos utilizados', null=True)),
                ('proximo_mantenimiento_km', models.PositiveIntegerField(blank=True, null=True)),
                ('proximo_mantenimiento_fecha', models.DateField(blank=True, null=True)),
                ('completado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='vehicles.vehiculo')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='AlertaMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('kilometraje_objetivo', models.PositiveIntegerField(blank=True, help_text='Kilometraje objetivo para el mantenimiento', null=True)),
                ('fecha_objetivo', models.DateField(blank=True, help_text='Fecha objetivo para el mantenimiento', null=True)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=10)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('mantenimiento_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='maintenance.mantenimiento')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_mantenimiento', to='vehicles.vehiculo')),
            ],
            options={
                'verbose_name': 'Alerta de Mantenimiento',
                'verbose_name_plural': 'Alertas de Mantenimiento',
                'ordering': ['-prioridad', 'fecha_objetivo'],
            },
        ),
    ]
