# Generated by Django 4.2.11 on 2025-12-27 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('año', models.PositiveIntegerField()),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('AUTO', 'Automóvil'), ('MOTO', 'Motocicleta'), ('CAMION', 'Camión'), ('SUV', 'SUV'), ('VAN', 'Van')], default='AUTO', max_length=10)),
                ('kilometraje_actual', models.PositiveIntegerField(default=0)),
                ('capacidad_tanque', models.DecimalField(decimal_places=2, help_text='Capacidad en litros', max_digits=5)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('numero_motor', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_chasis', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
