# Generated by Django 4.2.11 on 2025-12-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='capacidad_tanque',
            field=models.DecimalField(decimal_places=2, help_text='Capacidad del tanque en galones', max_digits=5),
        ),
    ]
